// <auto-generated />
namespace QuestRooms.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class add_numberhouse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_numberhouse));
        
        string IMigrationMetadata.Id
        {
            get { return "201908221425218_add_numberhouse"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
